set number
set relativenumber
set history=200
set noswapfile
set hidden
set undofile
set undodir=$HOME/.config/undo
set undolevels=10000
set undoreload=10000
let g:mapleader="\<space>"
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set ignorecase
set smartcase
set cursorline
set cursorcolumn
